import { RankDefinition } from '../store/types';

export const RANK_DEFINITIONS: readonly RankDefinition[] = [
  {
    key: 'E',
    title: 'Ordinary Human',
    minConsistency: 0,
    minLevel: 1,
    color: '#6B7280',
    glowColor: 'rgba(107, 114, 128, 0.4)',
    auraType: 'none',
  },
  {
    key: 'D',
    title: 'Hunter Initiate',
    minConsistency: 30,
    minLevel: 5,
    color: '#22C55E',
    glowColor: 'rgba(34, 197, 94, 0.4)',
    auraType: 'pulse',
  },
  {
    key: 'C',
    title: 'Proven Hunter',
    minConsistency: 50,
    minLevel: 15,
    color: '#3B82F6',
    glowColor: 'rgba(59, 130, 246, 0.4)',
    auraType: 'glow',
  },
  {
    key: 'B',
    title: 'Elite Hunter',
    minConsistency: 65,
    minLevel: 30,
    color: '#A855F7',
    glowColor: 'rgba(168, 85, 247, 0.4)',
    auraType: 'ring',
  },
  {
    key: 'A',
    title: 'Shadow Hunter',
    minConsistency: 78,
    minLevel: 50,
    color: '#F59E0B',
    glowColor: 'rgba(245, 158, 11, 0.4)',
    auraType: 'flare',
  },
  {
    key: 'S',
    title: 'Sovereign',
    minConsistency: 88,
    minLevel: 70,
    color: '#EF4444',
    glowColor: 'rgba(239, 68, 68, 0.4)',
    auraType: 'shockwave',
  },
  {
    key: 'SS',
    title: 'Monarch',
    minConsistency: 95,
    minLevel: 85,
    color: '#F97316',
    glowColor: 'rgba(249, 115, 22, 0.4)',
    auraType: 'flame',
  },
  {
    key: 'SSS',
    title: 'Immortal',
    minConsistency: 99,
    minLevel: 95,
    color: '#FFFFFF',
    glowColor: 'rgba(255, 255, 255, 0.4)',
    auraType: 'prismatic',
  },
];
